# Generated by Django 4.1.7 on 2023-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='default_password', max_length=50),
        ),
    ]
